version: 2.1

# required for dynamic configuration feature
# setup: true
setup: << pipeline.parameters.run-setup >>

orbs:
  # continuation: circleci/continuation@0.1.2
  path-filtering: circleci/path-filtering@0.0.3

parameters:
  run-setup:
    type: boolean
    default: true

  run-docs-only:
    type: boolean
    default: false

  run-full-build:
    type: boolean
    default: false

jobs:
  docs-only:
    docker:
      - image: alpine
    steps:
      - run: "echo 'Running only a docs change'"

  full-build:
    docker:
      - image: alpine
    steps:
      - run: "echo 'Running a full Electron build.'"

workflows:
  pre:
    when: << pipeline.parameters.run-setup >>
    jobs:
      - path-filtering/filter:
          # Compare files on all branches, using the webhook payload from Github
          base-revision: << pipeline.git.branch >>
          config-path: .circleci/config.yml
          # Params for mapping; `path-to-test parameter-to-set value-for-parameter` for each row
          mapping: |
            .* run-setup false
            ^((?!docs/).)*$ run-full-build true
            src/electron/docs/.* run-docs-only true
  docs-only:
    when: << pipeline.parameters.run-docs-only >>
    jobs:
      - docs-only
  full-build:
    when: << pipeline.parameters.run-full-build >>
    jobs:
      - full-build
